server {
    listen 80;
    listen [::]:80;
    server_name gp.mosreg.alenos.ru;

    root /var/www/gp.mosreg.alenos.ru;
    index index.html;

    charset utf-8;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /healthz {
        return 200 "ok\n";
    }
}
